language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'slush-element' ]; then cd .. && eval "mv $currentfolder slush-element" && cd slush-element; fi